import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientFooter } from "./components/ClientFooter";
import { ButtonNavbar } from "./components/ButtonNavbar";
import { AdminButtonNavbar } from "./components/AdminButtonNavbar";
import { Providers } from "./components/Providers";
import { ChatWidget } from "./components/ChatWidget";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
          <ClientFooter />
          <ButtonNavbar />
          <AdminButtonNavbar />
          <ChatWidget />
        </Providers>
      </body>
    </html>
  );
}
